//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a allus Code Generator.
//     Runtime Version: 1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;
using Fwk.Bases;

namespace Fwk.SocialNetworks.Common.BE
{

    [XmlRoot("PostList"), SerializableAttribute]
    public class PostList : Entities<Post>
    { }

    [XmlInclude(typeof(Post)), Serializable]
    public class Post : Entity
    {
        #region [Private Members]
        private System.Int32 _PostID;

        private System.String _Message;

        private System.DateTime _CreationDate;

        private System.Int32 _FromUserID;

        private System.Int32? _ToUserID;

        private System.String _SourcePostID;

        private System.Int32 _SocialNetworkID;

        private System.String _AppSourceID;

        private System.String _Permlink;

        private System.Int32? _ParentPostID;


        #endregion

        #region [Properties]
        #region [PostID]
        public System.Int32 PostID
        {
            get { return _PostID; }
            set { _PostID = value; }
        }
        #endregion


        #region [Message]
        public System.String Message
        {
            get { return _Message; }
            set { _Message = value; }
        }
        #endregion


        #region [CreationDate]
        public System.DateTime CreationDate
        {
            get { return _CreationDate; }
            set { _CreationDate = value; }
        }
        #endregion


        #region [FromUserID]
        public System.Int32 FromUserID
        {
            get { return _FromUserID; }
            set { _FromUserID = value; }
        }
        #endregion


        #region [ToUserID]
        public System.Int32? ToUserID
        {
            get { return _ToUserID; }
            set { _ToUserID = value; }
        }
        #endregion


        #region [SourcePostID]
        public System.String SourcePostID
        {
            get { return _SourcePostID; }
            set { _SourcePostID = value; }
        }
        #endregion


        #region [SocialNetworkID]
        public System.Int32 SocialNetworkID
        {
            get { return _SocialNetworkID; }
            set { _SocialNetworkID = value; }
        }
        #endregion


        #region [AppSourceID]
        public System.String AppSourceID
        {
            get { return _AppSourceID; }
            set { _AppSourceID = value; }
        }
        #endregion


        #region [Permlink]
        public System.String Permlink
        {
            get { return _Permlink; }
            set { _Permlink = value; }
        }
        #endregion


        #region [ParentPostID]
        public System.Int32? ParentPostID
        {
            get { return _ParentPostID; }
            set { _ParentPostID = value; }
        }
        #endregion



        #endregion


        public  Fwk.SocialNetworks.Data.Post GetModel()
        {
            Fwk.SocialNetworks.Data.Post modelPost = new Fwk.SocialNetworks.Data.Post();

            modelPost.Message = this.Message;
            modelPost.SourcePostID = this.SourcePostID;
            modelPost.SocialNetworkID =this.SocialNetworkID;
            modelPost.CreationDate = this.CreationDate;
            modelPost.FromUserID = this.FromUserID;
            modelPost.Permlink = this.Permlink;
            modelPost.ParentPostID = this.ParentPostID;
            modelPost.ToUserID = this.ToUserID;
            return modelPost;
        }


        public static Fwk.SocialNetworks.Common.BE.Post GetModel(Fwk.SocialNetworks.Data.Post pModelPost)
        {
            Fwk.SocialNetworks.Common.BE.Post post = new Fwk.SocialNetworks.Common.BE.Post();

            post.Message = pModelPost.Message;
            post.SourcePostID = pModelPost.SourcePostID;
            post.SocialNetworkID = pModelPost.SocialNetworkID;
            post.CreationDate = pModelPost.CreationDate;
            post.FromUserID = pModelPost.FromUserID;
            post.Permlink = pModelPost.Permlink;
            post.ParentPostID = pModelPost.ParentPostID;
            post.ToUserID = pModelPost.ToUserID;
            return post;
        } 
    }


}



