// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var carviewmodel = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'TRIS.ViewModels.CarViewModel, TRIS.ViewModels';

	self.co2 = ko.observable();
	self.importdate = ko.observable();
	self.options = ko.observableArray();
	self.availableyears = ko.observableArray();
	self.availablecountries = ko.observableArray();
	self.brand = ko.observable();
	self.model = ko.observable();
	self.id = ko.observable();
	self.isactive = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.Initialize();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.co2(objFromServer.co2);
	  if (objFromServer.importdate)
		self.importdate(moment(objFromServer.importdate).toDate());
	  else
	    self.importdate(null);
	  self.options.removeAll();	// clear array first
	  if (objFromServer.options && objFromServer.options.length > 0)
	  {
		  for (var i=0; i < objFromServer.options.length; i++) {
			  var _iter_item = objFromServer.options[i];
			  				  var _new_item = new optionviewmodel();
				  _new_item.setModel(_iter_item);
				  self.options.push(_new_item);
			  		  }
	  }
	  self.availableyears.removeAll();	// clear array first
	  if (objFromServer.availableyears && objFromServer.availableyears.length > 0)
	  {
		  for (var i=0; i < objFromServer.availableyears.length; i++) {
			  var _iter_item = objFromServer.availableyears[i];
			  				  self.availableyears.push(_iter_item);
			  		  }
	  }
	  self.availablecountries.removeAll();	// clear array first
	  if (objFromServer.availablecountries && objFromServer.availablecountries.length > 0)
	  {
		  for (var i=0; i < objFromServer.availablecountries.length; i++) {
			  var _iter_item = objFromServer.availablecountries[i];
			  				  self.availablecountries.push(_iter_item);
			  		  }
	  }
	  self.brand(objFromServer.brand);
	  self.model(objFromServer.model);
	  self.id(objFromServer.id);
	  self.isactive(objFromServer.isactive);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
carviewmodel.prototype = new extendable();

