//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Clinica1Model", "FK_TipoParametro_TipoParametro", "TipoParametro", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Health.Back.BE.TipoParametro), "TipoParametro1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Health.Back.BE.TipoParametro), true)]
[assembly: EdmRelationshipAttribute("Clinica1Model", "FK_ParamComercial_TipoParametro", "TipoParametro", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Health.Back.BE.TipoParametro), "Parametro", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Health.Back.BE.Parametro), true)]
[assembly: EdmRelationshipAttribute("Clinica1Model", "FK_Persona_Parametros", "Parametro", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Health.Back.BE.Parametro), "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Health.Back.BE.Persona), true)]
[assembly: EdmRelationshipAttribute("Clinica1Model", "FK_Paciente_Persona", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Health.Back.BE.Persona), "Patient", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Health.Back.BE.Patient), true)]
[assembly: EdmRelationshipAttribute("Clinica1Model", "FK_Consulta_ParamComercial", "Parametro", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Health.Back.BE.Parametro), "Consulta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Health.Back.BE.Consulta), true)]

#endregion

namespace Health.Back.BE
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HealthEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HealthEntities object using the connection string found in the 'HealthEntities' section of the application configuration file.
        /// </summary>
        public HealthEntities() : base("name=HealthEntities", "HealthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HealthEntities object.
        /// </summary>
        public HealthEntities(string connectionString) : base(connectionString, "HealthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HealthEntities object.
        /// </summary>
        public HealthEntities(EntityConnection connection) : base(connection, "HealthEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoParametro> TipoParametroes
        {
            get
            {
                if ((_TipoParametroes == null))
                {
                    _TipoParametroes = base.CreateObjectSet<TipoParametro>("TipoParametroes");
                }
                return _TipoParametroes;
            }
        }
        private ObjectSet<TipoParametro> _TipoParametroes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Parametro> Parametros
        {
            get
            {
                if ((_Parametros == null))
                {
                    _Parametros = base.CreateObjectSet<Parametro>("Parametros");
                }
                return _Parametros;
            }
        }
        private ObjectSet<Parametro> _Parametros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient> Patients
        {
            get
            {
                if ((_Patients == null))
                {
                    _Patients = base.CreateObjectSet<Patient>("Patients");
                }
                return _Patients;
            }
        }
        private ObjectSet<Patient> _Patients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Persona> Personas
        {
            get
            {
                if ((_Personas == null))
                {
                    _Personas = base.CreateObjectSet<Persona>("Personas");
                }
                return _Personas;
            }
        }
        private ObjectSet<Persona> _Personas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Consulta> Consultas
        {
            get
            {
                if ((_Consultas == null))
                {
                    _Consultas = base.CreateObjectSet<Consulta>("Consultas");
                }
                return _Consultas;
            }
        }
        private ObjectSet<Consulta> _Consultas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CEI10_Temp> CEI10_Temp
        {
            get
            {
                if ((_CEI10_Temp == null))
                {
                    _CEI10_Temp = base.CreateObjectSet<CEI10_Temp>("CEI10_Temp");
                }
                return _CEI10_Temp;
            }
        }
        private ObjectSet<CEI10_Temp> _CEI10_Temp;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoParametroes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoParametroes(TipoParametro tipoParametro)
        {
            base.AddObject("TipoParametroes", tipoParametro);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Parametros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParametros(Parametro parametro)
        {
            base.AddObject("Parametros", parametro);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Patients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatients(Patient patient)
        {
            base.AddObject("Patients", patient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Personas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPersonas(Persona persona)
        {
            base.AddObject("Personas", persona);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Consultas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConsultas(Consulta consulta)
        {
            base.AddObject("Consultas", consulta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CEI10_Temp EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCEI10_Temp(CEI10_Temp cEI10_Temp)
        {
            base.AddObject("CEI10_Temp", cEI10_Temp);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="CEI10_Temp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CEI10_Temp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CEI10_Temp object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="code">Initial value of the Code property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="parentCode">Initial value of the ParentCode property.</param>
        public static CEI10_Temp CreateCEI10_Temp(global::System.Int32 id, global::System.String code, global::System.String description, global::System.String parentCode)
        {
            CEI10_Temp cEI10_Temp = new CEI10_Temp();
            cEI10_Temp.Id = id;
            cEI10_Temp.Code = code;
            cEI10_Temp.Description = description;
            cEI10_Temp.ParentCode = parentCode;
            return cEI10_Temp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Code
        {
            get
            {
                return _Code;
            }
            set
            {
                if (_Code != value)
                {
                    OnCodeChanging(value);
                    ReportPropertyChanging("Code");
                    _Code = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Code");
                    OnCodeChanged();
                }
            }
        }
        private global::System.String _Code;
        partial void OnCodeChanging(global::System.String value);
        partial void OnCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ParentCode
        {
            get
            {
                return _ParentCode;
            }
            set
            {
                OnParentCodeChanging(value);
                ReportPropertyChanging("ParentCode");
                _ParentCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ParentCode");
                OnParentCodeChanged();
            }
        }
        private global::System.String _ParentCode;
        partial void OnParentCodeChanging(global::System.String value);
        partial void OnParentCodeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="Consulta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Consulta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Consulta object.
        /// </summary>
        /// <param name="idConsulta">Initial value of the IdConsulta property.</param>
        /// <param name="fecha">Initial value of the Fecha property.</param>
        public static Consulta CreateConsulta(global::System.Int32 idConsulta, global::System.DateTime fecha)
        {
            Consulta consulta = new Consulta();
            consulta.IdConsulta = idConsulta;
            consulta.Fecha = fecha;
            return consulta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdConsulta
        {
            get
            {
                return _IdConsulta;
            }
            set
            {
                if (_IdConsulta != value)
                {
                    OnIdConsultaChanging(value);
                    ReportPropertyChanging("IdConsulta");
                    _IdConsulta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdConsulta");
                    OnIdConsultaChanged();
                }
            }
        }
        private global::System.Int32 _IdConsulta;
        partial void OnIdConsultaChanging(global::System.Int32 value);
        partial void OnIdConsultaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoConsulta
        {
            get
            {
                return _IdTipoConsulta;
            }
            set
            {
                OnIdTipoConsultaChanging(value);
                ReportPropertyChanging("IdTipoConsulta");
                _IdTipoConsulta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoConsulta");
                OnIdTipoConsultaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoConsulta;
        partial void OnIdTipoConsultaChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoConsultaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdProfecional
        {
            get
            {
                return _IdProfecional;
            }
            set
            {
                OnIdProfecionalChanging(value);
                ReportPropertyChanging("IdProfecional");
                _IdProfecional = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProfecional");
                OnIdProfecionalChanged();
            }
        }
        private Nullable<global::System.Int32> _IdProfecional;
        partial void OnIdProfecionalChanging(Nullable<global::System.Int32> value);
        partial void OnIdProfecionalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdMutual
        {
            get
            {
                return _IdMutual;
            }
            set
            {
                OnIdMutualChanging(value);
                ReportPropertyChanging("IdMutual");
                _IdMutual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdMutual");
                OnIdMutualChanged();
            }
        }
        private Nullable<global::System.Int32> _IdMutual;
        partial void OnIdMutualChanging(Nullable<global::System.Int32> value);
        partial void OnIdMutualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NroAfiliadoMutual
        {
            get
            {
                return _NroAfiliadoMutual;
            }
            set
            {
                OnNroAfiliadoMutualChanging(value);
                ReportPropertyChanging("NroAfiliadoMutual");
                _NroAfiliadoMutual = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NroAfiliadoMutual");
                OnNroAfiliadoMutualChanged();
            }
        }
        private global::System.String _NroAfiliadoMutual;
        partial void OnNroAfiliadoMutualChanging(global::System.String value);
        partial void OnNroAfiliadoMutualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private global::System.DateTime _Fecha;
        partial void OnFechaChanging(global::System.DateTime value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreCliente
        {
            get
            {
                return _NombreCliente;
            }
            set
            {
                OnNombreClienteChanging(value);
                ReportPropertyChanging("NombreCliente");
                _NombreCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreCliente");
                OnNombreClienteChanged();
            }
        }
        private global::System.String _NombreCliente;
        partial void OnNombreClienteChanging(global::System.String value);
        partial void OnNombreClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PresentaOrden
        {
            get
            {
                return _PresentaOrden;
            }
            set
            {
                OnPresentaOrdenChanging(value);
                ReportPropertyChanging("PresentaOrden");
                _PresentaOrden = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PresentaOrden");
                OnPresentaOrdenChanged();
            }
        }
        private Nullable<global::System.Boolean> _PresentaOrden;
        partial void OnPresentaOrdenChanging(Nullable<global::System.Boolean> value);
        partial void OnPresentaOrdenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelefonoCliente
        {
            get
            {
                return _TelefonoCliente;
            }
            set
            {
                OnTelefonoClienteChanging(value);
                ReportPropertyChanging("TelefonoCliente");
                _TelefonoCliente = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelefonoCliente");
                OnTelefonoClienteChanged();
            }
        }
        private global::System.String _TelefonoCliente;
        partial void OnTelefonoClienteChanging(global::System.String value);
        partial void OnTelefonoClienteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Coseguro
        {
            get
            {
                return _Coseguro;
            }
            set
            {
                OnCoseguroChanging(value);
                ReportPropertyChanging("Coseguro");
                _Coseguro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Coseguro");
                OnCoseguroChanged();
            }
        }
        private Nullable<global::System.Decimal> _Coseguro;
        partial void OnCoseguroChanging(Nullable<global::System.Decimal> value);
        partial void OnCoseguroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ExigeCoseguro
        {
            get
            {
                return _ExigeCoseguro;
            }
            set
            {
                OnExigeCoseguroChanging(value);
                ReportPropertyChanging("ExigeCoseguro");
                _ExigeCoseguro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExigeCoseguro");
                OnExigeCoseguroChanged();
            }
        }
        private Nullable<global::System.Boolean> _ExigeCoseguro;
        partial void OnExigeCoseguroChanging(Nullable<global::System.Boolean> value);
        partial void OnExigeCoseguroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ArancelMutual
        {
            get
            {
                return _ArancelMutual;
            }
            set
            {
                OnArancelMutualChanging(value);
                ReportPropertyChanging("ArancelMutual");
                _ArancelMutual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArancelMutual");
                OnArancelMutualChanged();
            }
        }
        private Nullable<global::System.Decimal> _ArancelMutual;
        partial void OnArancelMutualChanging(Nullable<global::System.Decimal> value);
        partial void OnArancelMutualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Consulta_ParamComercial", "Parametro")]
        public Parametro Parametro
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Consulta_ParamComercial", "Parametro").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Consulta_ParamComercial", "Parametro").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Parametro> ParametroReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Consulta_ParamComercial", "Parametro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Parametro>("Clinica1Model.FK_Consulta_ParamComercial", "Parametro", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="Parametro")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Parametro : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Parametro object.
        /// </summary>
        /// <param name="idParametro">Initial value of the IdParametro property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="vigente">Initial value of the Vigente property.</param>
        public static Parametro CreateParametro(global::System.Int32 idParametro, global::System.String nombre, global::System.Boolean vigente)
        {
            Parametro parametro = new Parametro();
            parametro.IdParametro = idParametro;
            parametro.Nombre = nombre;
            parametro.Vigente = vigente;
            return parametro;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdParametro
        {
            get
            {
                return _IdParametro;
            }
            set
            {
                if (_IdParametro != value)
                {
                    OnIdParametroChanging(value);
                    ReportPropertyChanging("IdParametro");
                    _IdParametro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdParametro");
                    OnIdParametroChanged();
                }
            }
        }
        private global::System.Int32 _IdParametro;
        partial void OnIdParametroChanging(global::System.Int32 value);
        partial void OnIdParametroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoParametro
        {
            get
            {
                return _IdTipoParametro;
            }
            set
            {
                OnIdTipoParametroChanging(value);
                ReportPropertyChanging("IdTipoParametro");
                _IdTipoParametro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoParametro");
                OnIdTipoParametroChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoParametro;
        partial void OnIdTipoParametroChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoParametroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdParametroRef
        {
            get
            {
                return _IdParametroRef;
            }
            set
            {
                OnIdParametroRefChanging(value);
                ReportPropertyChanging("IdParametroRef");
                _IdParametroRef = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdParametroRef");
                OnIdParametroRefChanged();
            }
        }
        private Nullable<global::System.Int32> _IdParametroRef;
        partial void OnIdParametroRefChanging(Nullable<global::System.Int32> value);
        partial void OnIdParametroRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Vigente
        {
            get
            {
                return _Vigente;
            }
            set
            {
                OnVigenteChanging(value);
                ReportPropertyChanging("Vigente");
                _Vigente = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Vigente");
                OnVigenteChanged();
            }
        }
        private global::System.Boolean _Vigente;
        partial void OnVigenteChanging(global::System.Boolean value);
        partial void OnVigenteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CompanyId
        {
            get
            {
                return _CompanyId;
            }
            set
            {
                OnCompanyIdChanging(value);
                ReportPropertyChanging("CompanyId");
                _CompanyId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CompanyId");
                OnCompanyIdChanged();
            }
        }
        private global::System.String _CompanyId;
        partial void OnCompanyIdChanging(global::System.String value);
        partial void OnCompanyIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_ParamComercial_TipoParametro", "TipoParametro")]
        public TipoParametro TipoParametro
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "TipoParametro").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "TipoParametro").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoParametro> TipoParametroReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "TipoParametro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoParametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "TipoParametro", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Persona_Parametros", "Persona")]
        public EntityCollection<Persona> Personas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Persona>("Clinica1Model.FK_Persona_Parametros", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Persona>("Clinica1Model.FK_Persona_Parametros", "Persona", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Consulta_ParamComercial", "Consulta")]
        public EntityCollection<Consulta> Consultas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Consulta>("Clinica1Model.FK_Consulta_ParamComercial", "Consulta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Consulta>("Clinica1Model.FK_Consulta_ParamComercial", "Consulta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="Patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Patient object.
        /// </summary>
        /// <param name="patientId">Initial value of the PatientId property.</param>
        /// <param name="idPersona">Initial value of the IdPersona property.</param>
        /// <param name="fechaAlta">Initial value of the FechaAlta property.</param>
        public static Patient CreatePatient(global::System.Int32 patientId, global::System.Int32 idPersona, global::System.DateTime fechaAlta)
        {
            Patient patient = new Patient();
            patient.PatientId = patientId;
            patient.IdPersona = idPersona;
            patient.FechaAlta = fechaAlta;
            return patient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientId
        {
            get
            {
                return _PatientId;
            }
            set
            {
                if (_PatientId != value)
                {
                    OnPatientIdChanging(value);
                    ReportPropertyChanging("PatientId");
                    _PatientId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PatientId");
                    OnPatientIdChanged();
                }
            }
        }
        private global::System.Int32 _PatientId;
        partial void OnPatientIdChanging(global::System.Int32 value);
        partial void OnPatientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPersona
        {
            get
            {
                return _IdPersona;
            }
            set
            {
                OnIdPersonaChanging(value);
                ReportPropertyChanging("IdPersona");
                _IdPersona = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPersona");
                OnIdPersonaChanged();
            }
        }
        private global::System.Int32 _IdPersona;
        partial void OnIdPersonaChanging(global::System.Int32 value);
        partial void OnIdPersonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return _FechaAlta;
            }
            set
            {
                OnFechaAltaChanging(value);
                ReportPropertyChanging("FechaAlta");
                _FechaAlta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaAlta");
                OnFechaAltaChanged();
            }
        }
        private global::System.DateTime _FechaAlta;
        partial void OnFechaAltaChanging(global::System.DateTime value);
        partial void OnFechaAltaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastAccessTime
        {
            get
            {
                return _LastAccessTime;
            }
            set
            {
                OnLastAccessTimeChanging(value);
                ReportPropertyChanging("LastAccessTime");
                _LastAccessTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccessTime");
                OnLastAccessTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastAccessTime;
        partial void OnLastAccessTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastAccessTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> LastAccessUserId
        {
            get
            {
                return _LastAccessUserId;
            }
            set
            {
                OnLastAccessUserIdChanging(value);
                ReportPropertyChanging("LastAccessUserId");
                _LastAccessUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccessUserId");
                OnLastAccessUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _LastAccessUserId;
        partial void OnLastAccessUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnLastAccessUserIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Paciente_Persona", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Clinica1Model.FK_Paciente_Persona", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Clinica1Model.FK_Paciente_Persona", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("Clinica1Model.FK_Paciente_Persona", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("Clinica1Model.FK_Paciente_Persona", "Persona", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Persona object.
        /// </summary>
        /// <param name="idPersona">Initial value of the IdPersona property.</param>
        /// <param name="tipoDocumento">Initial value of the TipoDocumento property.</param>
        /// <param name="nroDocumento">Initial value of the NroDocumento property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="sexo">Initial value of the Sexo property.</param>
        /// <param name="fechaNacimiento">Initial value of the FechaNacimiento property.</param>
        /// <param name="lastAccessTime">Initial value of the LastAccessTime property.</param>
        /// <param name="lastAccessUserId">Initial value of the LastAccessUserId property.</param>
        /// <param name="fechaAlta">Initial value of the FechaAlta property.</param>
        /// <param name="isUserActive">Initial value of the IsUserActive property.</param>
        public static Persona CreatePersona(global::System.Int32 idPersona, global::System.String tipoDocumento, global::System.String nroDocumento, global::System.String apellido, global::System.String nombre, global::System.Int16 sexo, global::System.DateTime fechaNacimiento, global::System.DateTime lastAccessTime, global::System.Guid lastAccessUserId, global::System.DateTime fechaAlta, global::System.Boolean isUserActive)
        {
            Persona persona = new Persona();
            persona.IdPersona = idPersona;
            persona.TipoDocumento = tipoDocumento;
            persona.NroDocumento = nroDocumento;
            persona.Apellido = apellido;
            persona.Nombre = nombre;
            persona.Sexo = sexo;
            persona.FechaNacimiento = fechaNacimiento;
            persona.LastAccessTime = lastAccessTime;
            persona.LastAccessUserId = lastAccessUserId;
            persona.FechaAlta = fechaAlta;
            persona.IsUserActive = isUserActive;
            return persona;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdPersona
        {
            get
            {
                return _IdPersona;
            }
            set
            {
                if (_IdPersona != value)
                {
                    OnIdPersonaChanging(value);
                    ReportPropertyChanging("IdPersona");
                    _IdPersona = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdPersona");
                    OnIdPersonaChanged();
                }
            }
        }
        private global::System.Int32 _IdPersona;
        partial void OnIdPersonaChanging(global::System.Int32 value);
        partial void OnIdPersonaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Guid> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Guid> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoDocumento
        {
            get
            {
                return _TipoDocumento;
            }
            set
            {
                OnTipoDocumentoChanging(value);
                ReportPropertyChanging("TipoDocumento");
                _TipoDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoDocumento");
                OnTipoDocumentoChanged();
            }
        }
        private global::System.String _TipoDocumento;
        partial void OnTipoDocumentoChanging(global::System.String value);
        partial void OnTipoDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NroDocumento
        {
            get
            {
                return _NroDocumento;
            }
            set
            {
                OnNroDocumentoChanging(value);
                ReportPropertyChanging("NroDocumento");
                _NroDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NroDocumento");
                OnNroDocumentoChanged();
            }
        }
        private global::System.String _NroDocumento;
        partial void OnNroDocumentoChanging(global::System.String value);
        partial void OnNroDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 Sexo
        {
            get
            {
                return _Sexo;
            }
            set
            {
                OnSexoChanging(value);
                ReportPropertyChanging("Sexo");
                _Sexo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sexo");
                OnSexoChanged();
            }
        }
        private global::System.Int16 _Sexo;
        partial void OnSexoChanging(global::System.Int16 value);
        partial void OnSexoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdEstadocivil
        {
            get
            {
                return _IdEstadocivil;
            }
            set
            {
                OnIdEstadocivilChanging(value);
                ReportPropertyChanging("IdEstadocivil");
                _IdEstadocivil = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEstadocivil");
                OnIdEstadocivilChanged();
            }
        }
        private Nullable<global::System.Int32> _IdEstadocivil;
        partial void OnIdEstadocivilChanging(Nullable<global::System.Int32> value);
        partial void OnIdEstadocivilChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaNacimiento
        {
            get
            {
                return _FechaNacimiento;
            }
            set
            {
                OnFechaNacimientoChanging(value);
                ReportPropertyChanging("FechaNacimiento");
                _FechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaNacimiento");
                OnFechaNacimientoChanged();
            }
        }
        private global::System.DateTime _FechaNacimiento;
        partial void OnFechaNacimientoChanging(global::System.DateTime value);
        partial void OnFechaNacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastAccessTime
        {
            get
            {
                return _LastAccessTime;
            }
            set
            {
                OnLastAccessTimeChanging(value);
                ReportPropertyChanging("LastAccessTime");
                _LastAccessTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccessTime");
                OnLastAccessTimeChanged();
            }
        }
        private global::System.DateTime _LastAccessTime;
        partial void OnLastAccessTimeChanging(global::System.DateTime value);
        partial void OnLastAccessTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid LastAccessUserId
        {
            get
            {
                return _LastAccessUserId;
            }
            set
            {
                OnLastAccessUserIdChanging(value);
                ReportPropertyChanging("LastAccessUserId");
                _LastAccessUserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAccessUserId");
                OnLastAccessUserIdChanged();
            }
        }
        private global::System.Guid _LastAccessUserId;
        partial void OnLastAccessUserIdChanging(global::System.Guid value);
        partial void OnLastAccessUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime FechaAlta
        {
            get
            {
                return _FechaAlta;
            }
            set
            {
                OnFechaAltaChanging(value);
                ReportPropertyChanging("FechaAlta");
                _FechaAlta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaAlta");
                OnFechaAltaChanged();
            }
        }
        private global::System.DateTime _FechaAlta;
        partial void OnFechaAltaChanging(global::System.DateTime value);
        partial void OnFechaAltaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Calle
        {
            get
            {
                return _Calle;
            }
            set
            {
                OnCalleChanging(value);
                ReportPropertyChanging("Calle");
                _Calle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Calle");
                OnCalleChanged();
            }
        }
        private global::System.String _Calle;
        partial void OnCalleChanging(global::System.String value);
        partial void OnCalleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CalleNumero
        {
            get
            {
                return _CalleNumero;
            }
            set
            {
                OnCalleNumeroChanging(value);
                ReportPropertyChanging("CalleNumero");
                _CalleNumero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CalleNumero");
                OnCalleNumeroChanged();
            }
        }
        private Nullable<global::System.Int16> _CalleNumero;
        partial void OnCalleNumeroChanging(Nullable<global::System.Int16> value);
        partial void OnCalleNumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Piso
        {
            get
            {
                return _Piso;
            }
            set
            {
                OnPisoChanging(value);
                ReportPropertyChanging("Piso");
                _Piso = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Piso");
                OnPisoChanged();
            }
        }
        private global::System.String _Piso;
        partial void OnPisoChanging(global::System.String value);
        partial void OnPisoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdPais
        {
            get
            {
                return _IdPais;
            }
            set
            {
                OnIdPaisChanging(value);
                ReportPropertyChanging("IdPais");
                _IdPais = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdPais");
                OnIdPaisChanged();
            }
        }
        private Nullable<global::System.Int32> _IdPais;
        partial void OnIdPaisChanging(Nullable<global::System.Int32> value);
        partial void OnIdPaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdProvincia
        {
            get
            {
                return _IdProvincia;
            }
            set
            {
                OnIdProvinciaChanging(value);
                ReportPropertyChanging("IdProvincia");
                _IdProvincia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdProvincia");
                OnIdProvinciaChanged();
            }
        }
        private Nullable<global::System.Int32> _IdProvincia;
        partial void OnIdProvinciaChanging(Nullable<global::System.Int32> value);
        partial void OnIdProvinciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdLocalidad
        {
            get
            {
                return _IdLocalidad;
            }
            set
            {
                OnIdLocalidadChanging(value);
                ReportPropertyChanging("IdLocalidad");
                _IdLocalidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdLocalidad");
                OnIdLocalidadChanged();
            }
        }
        private Nullable<global::System.Int32> _IdLocalidad;
        partial void OnIdLocalidadChanging(Nullable<global::System.Int32> value);
        partial void OnIdLocalidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barrio
        {
            get
            {
                return _Barrio;
            }
            set
            {
                OnBarrioChanging(value);
                ReportPropertyChanging("Barrio");
                _Barrio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Barrio");
                OnBarrioChanged();
            }
        }
        private global::System.String _Barrio;
        partial void OnBarrioChanging(global::System.String value);
        partial void OnBarrioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mail
        {
            get
            {
                return _mail;
            }
            set
            {
                OnmailChanging(value);
                ReportPropertyChanging("mail");
                _mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mail");
                OnmailChanged();
            }
        }
        private global::System.String _mail;
        partial void OnmailChanging(global::System.String value);
        partial void OnmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono1
        {
            get
            {
                return _Telefono1;
            }
            set
            {
                OnTelefono1Changing(value);
                ReportPropertyChanging("Telefono1");
                _Telefono1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono1");
                OnTelefono1Changed();
            }
        }
        private global::System.String _Telefono1;
        partial void OnTelefono1Changing(global::System.String value);
        partial void OnTelefono1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono2
        {
            get
            {
                return _Telefono2;
            }
            set
            {
                OnTelefono2Changing(value);
                ReportPropertyChanging("Telefono2");
                _Telefono2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono2");
                OnTelefono2Changed();
            }
        }
        private global::System.String _Telefono2;
        partial void OnTelefono2Changing(global::System.String value);
        partial void OnTelefono2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Foto
        {
            get
            {
                return StructuralObject.GetValidValue(_Foto);
            }
            set
            {
                OnFotoChanging(value);
                ReportPropertyChanging("Foto");
                _Foto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Foto");
                OnFotoChanged();
            }
        }
        private global::System.Byte[] _Foto;
        partial void OnFotoChanging(global::System.Byte[] value);
        partial void OnFotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsNaturalPerson
        {
            get
            {
                return _IsNaturalPerson;
            }
            set
            {
                OnIsNaturalPersonChanging(value);
                ReportPropertyChanging("IsNaturalPerson");
                _IsNaturalPerson = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNaturalPerson");
                OnIsNaturalPersonChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsNaturalPerson;
        partial void OnIsNaturalPersonChanging(Nullable<global::System.Boolean> value);
        partial void OnIsNaturalPersonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RazonSocial
        {
            get
            {
                return _RazonSocial;
            }
            set
            {
                OnRazonSocialChanging(value);
                ReportPropertyChanging("RazonSocial");
                _RazonSocial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RazonSocial");
                OnRazonSocialChanged();
            }
        }
        private global::System.String _RazonSocial;
        partial void OnRazonSocialChanging(global::System.String value);
        partial void OnRazonSocialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsUserActive
        {
            get
            {
                return _IsUserActive;
            }
            set
            {
                OnIsUserActiveChanging(value);
                ReportPropertyChanging("IsUserActive");
                _IsUserActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsUserActive");
                OnIsUserActiveChanged();
            }
        }
        private global::System.Boolean _IsUserActive;
        partial void OnIsUserActiveChanging(global::System.Boolean value);
        partial void OnIsUserActiveChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Persona_Parametros", "Parametro")]
        public Parametro Parametro
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Persona_Parametros", "Parametro").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Persona_Parametros", "Parametro").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Parametro> ParametroReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Parametro>("Clinica1Model.FK_Persona_Parametros", "Parametro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Parametro>("Clinica1Model.FK_Persona_Parametros", "Parametro", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_Paciente_Persona", "Patient")]
        public EntityCollection<Patient> Patients
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Patient>("Clinica1Model.FK_Paciente_Persona", "Patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Patient>("Clinica1Model.FK_Paciente_Persona", "Patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Clinica1Model", Name="TipoParametro")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoParametro : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoParametro object.
        /// </summary>
        /// <param name="idTipoParametro">Initial value of the IdTipoParametro property.</param>
        public static TipoParametro CreateTipoParametro(global::System.Int32 idTipoParametro)
        {
            TipoParametro tipoParametro = new TipoParametro();
            tipoParametro.IdTipoParametro = idTipoParametro;
            return tipoParametro;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdTipoParametro
        {
            get
            {
                return _IdTipoParametro;
            }
            set
            {
                if (_IdTipoParametro != value)
                {
                    OnIdTipoParametroChanging(value);
                    ReportPropertyChanging("IdTipoParametro");
                    _IdTipoParametro = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdTipoParametro");
                    OnIdTipoParametroChanged();
                }
            }
        }
        private global::System.Int32 _IdTipoParametro;
        partial void OnIdTipoParametroChanging(global::System.Int32 value);
        partial void OnIdTipoParametroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTipoParametroRelacion
        {
            get
            {
                return _IdTipoParametroRelacion;
            }
            set
            {
                OnIdTipoParametroRelacionChanging(value);
                ReportPropertyChanging("IdTipoParametroRelacion");
                _IdTipoParametroRelacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTipoParametroRelacion");
                OnIdTipoParametroRelacionChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTipoParametroRelacion;
        partial void OnIdTipoParametroRelacionChanging(Nullable<global::System.Int32> value);
        partial void OnIdTipoParametroRelacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_TipoParametro_TipoParametro", "TipoParametro1")]
        public EntityCollection<TipoParametro> TipoParametro1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_TipoParametro_TipoParametro", "TipoParametro")]
        public TipoParametro TipoParametro2
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoParametro> TipoParametro2Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoParametro>("Clinica1Model.FK_TipoParametro_TipoParametro", "TipoParametro", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Clinica1Model", "FK_ParamComercial_TipoParametro", "Parametro")]
        public EntityCollection<Parametro> Parametros
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Parametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "Parametro");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Parametro>("Clinica1Model.FK_ParamComercial_TipoParametro", "Parametro", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
