<?xml version="1.0" encoding="utf-8"?><Database Name="Health" EntityNamespace="Health.Entities" ContextNamespace="Health.Entities" Class="HealthLinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANTANA\SQLEXPRESS;Initial Catalog=Health;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="Health.Back.BE.Properties.Settings" SettingsPropertyName="HealthConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TipoParametro" Member="TipoParametros">
    <Type Name="TipoParametro">
      <Column Name="IdTipoParametro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IdTipoParametroRelacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TipoParametro_TipoParametro" Member="TipoParametros" ThisKey="IdTipoParametro" OtherKey="IdTipoParametroRelacion" Type="TipoParametro" />
      <Association Name="TipoParametro_Parametro" Member="Parametros" ThisKey="IdTipoParametro" OtherKey="IdTipoParametro" Type="Parametro" />
      <Association Name="TipoParametro_TipoParametro" Member="TipoParametro1" ThisKey="IdTipoParametroRelacion" OtherKey="IdTipoParametro" Type="TipoParametro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Parametro" Member="Parametros">
    <Type Name="Parametro">
      <Column Name="IdParametro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IdTipoParametro" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdParametroRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Vigente" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CompanyId" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="TipoParametro_Parametro" Member="TipoParametro" ThisKey="IdTipoParametro" OtherKey="IdTipoParametro" Type="TipoParametro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_Persona" Member="Personas" ThisKey="UserId" OtherKey="UserId" Type="Persona" />
    </Type>
  </Table>
  <Table Name="dbo.cei10_view" Member="cei10_views">
    <Type Name="cei10_view">
      <Column Name="Capitulo" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Grupo2" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Grupo1" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="HasChilds" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Nomenclator_AnalisisClinicos_temp" Member="Nomenclator_AnalisisClinicos_temps">
    <Type Name="Nomenclator_AnalisisClinicos_temp">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Nomenclators" Member="Nomenclators">
    <Type Name="Nomenclator">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCode" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="HasChilds" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PMOType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RegistrationRequest" Member="RegistrationRequests">
    <Type Name="RegistrationRequest">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="RegistrationCode" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="Matricula" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TipoDocumento" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="NroDocumento" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequetsTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Profesional" Member="Profesionals">
    <Type Name="Profesional">
      <Column Name="IdProfesional" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPersona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEspecialidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Matricula" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdProfesion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Persona_Profesional" Member="Persona" ThisKey="IdPersona" OtherKey="IdPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persona" Member="Personas">
    <Type Name="Persona">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TipoDocumento" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="NroDocumento" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadocivil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsUserActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="StreetNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Floor" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Neighborhood" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mail" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Telefono1" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Telefono2" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Association Name="Persona_Profesional" Member="Profesionals" ThisKey="IdPersona" OtherKey="IdPersona" Type="Profesional" />
      <Association Name="aspnet_User_Persona" Member="aspnet_User" ThisKey="UserId" OtherKey="UserId" Type="aspnet_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HealthInstitution" Member="HealthInstitutions">
    <Type Name="HealthInstitution">
      <Column Name="HealthInstitutionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HealthInstitutionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="StreetNumber" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Floor" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="CountryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProvinceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RazonSocial" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Province" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Neighborhood" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ZipCode" Type="System.String" DbType="Char(8)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ActivationKey" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="CUIT" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="HealthInstitutionIdParent" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HealthInstitutions_SuscriptionRequest" Member="HealthInstitutions_SuscriptionRequests">
    <Type Name="HealthInstitutions_SuscriptionRequest">
      <Column Name="HealthInstitutionId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProfesionalId_From" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Profesional_To" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnableFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RequestSend" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="RoleName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderIsOwner" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>