//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.1433
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://fwk", ClrNamespace = "fwk")]

namespace fwk
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MailMessage", Namespace = "http://fwk")]
    public partial class MailMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ToAddressField;

        private string FromAddressField;

        private string CCAddressField;

        private string BCCAddressField;

        private string SubjectField;

        private string BodyField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ToAddress
        {
            get
            {
                return this.ToAddressField;
            }
            set
            {
                this.ToAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public string FromAddress
        {
            get
            {
                return this.FromAddressField;
            }
            set
            {
                this.FromAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 2)]
        public string CCAddress
        {
            get
            {
                return this.CCAddressField;
            }
            set
            {
                this.CCAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Order = 3)]
        public string BCCAddress
        {
            get
            {
                return this.BCCAddressField;
            }
            set
            {
                this.BCCAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public string Body
        {
            get
            {
                return this.BodyField;
            }
            set
            {
                this.BodyField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://fwk", ConfigurationName = "ISendMail", CallbackContract = typeof(ISendMailCallback), SessionMode = System.ServiceModel.SessionMode.Required)]
public interface ISendMail
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://fwk/ISendMail/SubmitMessage")]
    void SubmitMessage(fwk.MailMessage message);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, AsyncPattern = true, Action = "http://fwk/ISendMail/SubmitMessage")]
    System.IAsyncResult BeginSubmitMessage(fwk.MailMessage message, System.AsyncCallback callback, object asyncState);

    void EndSubmitMessage(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISendMailCallback
{

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://fwk/ISendMail/Resived")]
    void Resived(int location);

    [System.ServiceModel.OperationContractAttribute(IsOneWay = true, AsyncPattern = true, Action = "http://fwk/ISendMail/Resived")]
    System.IAsyncResult BeginResived(int location, System.AsyncCallback callback, object asyncState);

    void EndResived(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISendMailChannel : ISendMail, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SendMailClient : System.ServiceModel.DuplexClientBase<ISendMail>, ISendMail
{

    public SendMailClient(System.ServiceModel.InstanceContext callbackInstance) :
        base(callbackInstance)
    {
    }

    public SendMailClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
        base(callbackInstance, endpointConfigurationName)
    {
    }

    public SendMailClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public SendMailClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }

    public SendMailClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(callbackInstance, binding, remoteAddress)
    {
    }

    public void SubmitMessage(fwk.MailMessage message)
    {
        base.Channel.SubmitMessage(message);
    }

    public System.IAsyncResult BeginSubmitMessage(fwk.MailMessage message, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginSubmitMessage(message, callback, asyncState);
    }

    public void EndSubmitMessage(System.IAsyncResult result)
    {
        base.Channel.EndSubmitMessage(result);
    }
}
