<?xml version="1.0" encoding="utf-8"?>
<Database Name="AdventureWorks" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local)\sqlexpress;Initial Catalog=AdventureWorks;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AdventureWorksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TotalAmountByProductByYear" Member="TotalAmountByProductByYears">
    <Type Name="TotalAmountByProductByYear">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>