<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://tempuri.org/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" targetNamespace="http://tempuri.org/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://tempuri.org/Imports">
      <xsd:import namespace="http://tempuri.org/" />
      <xsd:import namespace="http://schemas.microsoft.com/2003/10/Serialization/" />
      <xsd:import namespace="http://schemas.datacontract.org/2004/07/Common" />
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="IChat_Say_InputMessage">
    <wsdl:part name="parameters" element="tns:Say" />
  </wsdl:message>
  <wsdl:message name="IChat_Whisper_InputMessage">
    <wsdl:part name="parameters" element="tns:Whisper" />
  </wsdl:message>
  <wsdl:message name="IChat_Join_InputMessage">
    <wsdl:part name="parameters" element="tns:Join" />
  </wsdl:message>
  <wsdl:message name="IChat_Join_OutputMessage">
    <wsdl:part name="parameters" element="tns:JoinResponse" />
  </wsdl:message>
  <wsdl:message name="IChat_Leave_InputMessage">
    <wsdl:part name="parameters" element="tns:Leave" />
  </wsdl:message>
  <wsdl:message name="IChat_Receive_OutputCallbackMessage">
    <wsdl:part name="parameters" element="tns:Receive" />
  </wsdl:message>
  <wsdl:message name="IChat_ReceiveWhisper_OutputCallbackMessage">
    <wsdl:part name="parameters" element="tns:ReceiveWhisper" />
  </wsdl:message>
  <wsdl:message name="IChat_UserEnter_OutputCallbackMessage">
    <wsdl:part name="parameters" element="tns:UserEnter" />
  </wsdl:message>
  <wsdl:message name="IChat_UserLeave_OutputCallbackMessage">
    <wsdl:part name="parameters" element="tns:UserLeave" />
  </wsdl:message>
  <wsdl:portType msc:usingSession="true" name="IChat">
    <wsdl:operation msc:isInitiating="false" msc:isTerminating="false" name="Say">
      <wsdl:input wsaw:Action="http://tempuri.org/IChat/Say" message="tns:IChat_Say_InputMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="false" msc:isTerminating="false" name="Whisper">
      <wsdl:input wsaw:Action="http://tempuri.org/IChat/Whisper" message="tns:IChat_Whisper_InputMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="true" msc:isTerminating="false" name="Join">
      <wsdl:input wsaw:Action="http://tempuri.org/IChat/Join" message="tns:IChat_Join_InputMessage" />
      <wsdl:output wsaw:Action="http://tempuri.org/IChat/JoinResponse" message="tns:IChat_Join_OutputMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="false" msc:isTerminating="true" name="Leave">
      <wsdl:input wsaw:Action="http://tempuri.org/IChat/Leave" message="tns:IChat_Leave_InputMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="true" msc:isTerminating="false" name="Receive">
      <wsdl:output wsaw:Action="http://tempuri.org/IChat/Receive" message="tns:IChat_Receive_OutputCallbackMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="true" msc:isTerminating="false" name="ReceiveWhisper">
      <wsdl:output wsaw:Action="http://tempuri.org/IChat/ReceiveWhisper" message="tns:IChat_ReceiveWhisper_OutputCallbackMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="true" msc:isTerminating="false" name="UserEnter">
      <wsdl:output wsaw:Action="http://tempuri.org/IChat/UserEnter" message="tns:IChat_UserEnter_OutputCallbackMessage" />
    </wsdl:operation>
    <wsdl:operation msc:isInitiating="true" msc:isTerminating="false" name="UserLeave">
      <wsdl:output wsaw:Action="http://tempuri.org/IChat/UserLeave" message="tns:IChat_UserLeave_OutputCallbackMessage" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="DefaultBinding_IChat" type="tns:IChat">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="Say">
      <soap:operation soapAction="http://tempuri.org/IChat/Say" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="Whisper">
      <soap:operation soapAction="http://tempuri.org/IChat/Whisper" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="Join">
      <soap:operation soapAction="http://tempuri.org/IChat/Join" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Leave">
      <soap:operation soapAction="http://tempuri.org/IChat/Leave" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
    </wsdl:operation>
    <wsdl:operation name="Receive">
      <soap:operation soapAction="http://tempuri.org/IChat/Receive" style="document" />
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="ReceiveWhisper">
      <soap:operation soapAction="http://tempuri.org/IChat/ReceiveWhisper" style="document" />
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UserEnter">
      <soap:operation soapAction="http://tempuri.org/IChat/UserEnter" style="document" />
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="UserLeave">
      <soap:operation soapAction="http://tempuri.org/IChat/UserLeave" style="document" />
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
</wsdl:definitions>