//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pelsoft.FWK_Dsl.DslPackage
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "fwkdsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"FWK_Dsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"pelsoft";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID FWK_DslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FWK_DslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID FWK_DslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FWK_DslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewFWK_DslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(FWK_DslCommandSetId), 0x0001);
	
		// Package identifier
		public const string FWK_DslPackageId = "54776c82-4666-483e-a7bb-397b397f03c0";
		
		// Editor factory identifier
		public const string FWK_DslEditorFactoryId = "bed5263b-042e-49e2-8d4f-167124a5a860";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string FWK_DslModelExplorerToolWindowId = "773b9a90-9caf-42e9-86f7-a13362a9ee1e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace pelsoft.FWK_Dsl.DslPackage
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string FWK_DslCommandSetId = "b9517dd2-43c8-4a2c-abea-955321c7b391";
	}
}