//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysEvent.Common.ServiceProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxy.ISystemEvent")]
    public interface ISystemEvent {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISystemEvent/SubmitMessage_Queue")]
        void SubmitMessage_Queue(SysEvent.Common.ServiceProxy.SubmitMessage_Queue request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SubmitMessage_Queue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SubmitMessage_Queue {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.DateTime time;
        
        public SubmitMessage_Queue() {
        }
        
        public SubmitMessage_Queue(byte[] message, System.DateTime time) {
            this.message = message;
            this.time = time;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISystemEventChannel : SysEvent.Common.ServiceProxy.ISystemEvent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SystemEventClient : System.ServiceModel.ClientBase<SysEvent.Common.ServiceProxy.ISystemEvent>, SysEvent.Common.ServiceProxy.ISystemEvent {
        
        public SystemEventClient() {
        }
        
        public SystemEventClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemEventClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemEventClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemEventClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitMessage_Queue(SysEvent.Common.ServiceProxy.SubmitMessage_Queue request) {
            base.Channel.SubmitMessage_Queue(request);
        }
    }
}
