<?xml version="1.0" encoding="utf-8"?><Database Name="HCapote" EntityNamespace="ShoppingCart" ContextNamespace="ShoppingCart" Class="DelfinDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SANTANA\SQLEXPRESS2008R2;Initial Catalog=HCapote;User ID=ws" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HCapoteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.categoria" Member="categorias">
    <Type Name="categoria">
      <Column Name="idcate" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idparent" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="idnivel" Type="System.String" DbType="Char(25) NOT NULL" CanBeNull="false" />
      <Column Name="denom" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="poriva" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="marguia" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="idregistro" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="iduser" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="fechor" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="depto" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
      <Column Name="catego" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="idgrupocate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="iddepto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="comisionguia" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Association Name="categoria_articulo" Member="articulos" ThisKey="idcate" OtherKey="idcate" Type="articulo" />
    </Type>
  </Table>
  <Table Name="dbo.articulo" Member="articulos">
    <Type Name="articulo">
      <Column Name="idregistro" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="idart" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="idunimed" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="idcate" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="idmarca" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Column Name="idprov" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="denom" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="denred" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="contenido" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="pesable" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="disc_int" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_cmp" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_vta" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_stk" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_pro" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_den" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="tipo_pre" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="ctrl_stk" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="base" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="decto1" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto2" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto3" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto4" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto5" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto6" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="decto7" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="porfle" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="flete" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="porrec" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="recargo" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="pormer" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="bonmer" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="costosini" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="poriva" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="totiva" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="costoconi" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="porint" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="impinter" Type="System.Decimal" DbType="Decimal(12,5)" CanBeNull="true" />
      <Column Name="idctavta" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="iduser" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="fechor" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ccompra" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="cventa" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="idctacmp" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="idseccion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rubro_pro" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="afectado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fechacreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="notas" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="senasa" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="product_id" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="articulo_codbarra" Member="codbarras" ThisKey="idart" OtherKey="idart" Type="codbarra" />
      <Association Name="categoria_articulo" Member="categoria" ThisKey="idcate" OtherKey="idcate" Type="categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.codbarra" Member="codbarras">
    <Type Name="codbarra">
      <Column Name="idcodint" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idart" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="barra" Type="System.String" DbType="Char(16) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="barracon" Type="System.String" DbType="Char(16)" CanBeNull="true" />
      <Column Name="habilitado" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="uencon" Type="System.Decimal" DbType="Decimal(4,0)" CanBeNull="true" />
      <Column Name="unibul" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="tipo" Type="System.Decimal" DbType="Decimal(1,0) NOT NULL" CanBeNull="false" />
      <Column Name="codpro" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="marguia" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="margen" Type="System.Decimal" DbType="Decimal(6,2)" CanBeNull="true" />
      <Column Name="prevta" Type="System.Decimal" DbType="Decimal(11,5) NOT NULL" CanBeNull="false" />
      <Column Name="idregistro" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="anchobul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="largobul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="altobul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="volbul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="pesonetbul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="pesobrubul" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="bultopal" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="bultohil" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="hilpal" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="pesopal" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="altopal" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="volpal" Type="System.Decimal" DbType="Decimal(7,4)" CanBeNull="true" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="iduser" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="fechor" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="uconten" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="prevtasi" Type="System.Decimal" DbType="Decimal(11,5) NOT NULL" CanBeNull="false" />
      <Column Name="caduca" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="comision" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="idcolor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtalle" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idmedidatex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechacreacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="identificador" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="idpais" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Association Name="articulo_codbarra" Member="articulo" ThisKey="idart" OtherKey="idart" Type="articulo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.shopcart_products_view" Member="shopcart_products_views">
    <Type Name="shopcart_products_view">
      <Column Name="idart" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="idcate" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="prevta" Type="System.Decimal" DbType="Decimal(11,5)" CanBeNull="true" />
      <Column Name="denom" Type="System.String" DbType="Char(40) NOT NULL" CanBeNull="false" />
      <Column Name="Marca" Type="System.String" DbType="Char(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>