<?xml version="1.0" encoding="utf-8"?>
<Database Name="AdventureWorks" Class="CustomerEntityDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=matu\sqlexpress;Initial Catalog=AdventureWorks;Integrated Security=True" SettingsObjectName="TestPerformanceLinQ.BackEnd.Properties.Settings" SettingsPropertyName="AdventureWorksConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="Sales.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="VarChar(10) NOT NULL" IsDbGenerated="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CustomerType" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Customer_CustomerAddress" Member="CustomerAddresses" ThisKey="CustomerID" OtherKey="CustomerID" Type="CustomerAddress" />
    </Type>
  </Table>
  <Table Name="Sales.CustomerAddress" Member="CustomerAddresses">
    <Type Name="CustomerAddress">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddressTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="rowguid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Customer_CustomerAddress" Member="Customer" ThisKey="CustomerID" OtherKey="CustomerID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>