<?xml version="1.0" encoding="utf-8"?><Database Name="Health" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANTANA\SQLEXPRESS;Initial Catalog=Health;Integrated Security=True" SettingsObjectName="Scheduler.Properties.Settings" SettingsPropertyName="HealthConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Profecional" Member="Profecionals">
    <Type Name="Profecional">
      <Column Name="IdProfecional" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPersona" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEspecialidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Matricula" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Persona_Profecional" Member="Persona" ThisKey="IdPersona" OtherKey="IdPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Paciente" Member="Pacientes">
    <Type Name="Paciente">
      <Column Name="IdPaciente" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Persona_Paciente" Member="Persona" ThisKey="IdPersona" OtherKey="IdPersona" Type="Persona" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Persona" Member="Personas">
    <Type Name="Persona">
      <Column Name="IdPersona" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="TipoDocumento" Type="System.String" DbType="Char(4) NOT NULL" CanBeNull="false" />
      <Column Name="NroDocumento" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="IdEstadocivil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaNacimiento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccessUserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FechaAlta" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Persona_Profecional" Member="Profecionals" ThisKey="IdPersona" OtherKey="IdPersona" Type="Profecional" />
      <Association Name="Persona_Paciente" Member="Pacientes" ThisKey="IdPersona" OtherKey="IdPersona" Type="Paciente" />
    </Type>
  </Table>
  <Table Name="dbo.Appointments" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="IdAppoiment" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Start" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[End]" Member="End" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ResourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Label" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllDay" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DayNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekOfMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OccurrenceCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Periodicity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Range" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdProfecional" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdPaciente" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Duration" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ResourceScheduling" Member="ResourceSchedulings">
    <Type Name="ResourceScheduling">
      <Column Name="IdSheduler" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DateStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ResourceId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekOfMonth" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WeekDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Duration" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreationUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UpdateUserId" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ResourceType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeStart" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TimeEnd" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
</Database>