//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a allus Code Generator.
//     Runtime Version: 1.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;
using Fwk.Bases;

namespace WebChat.Common.BE
{
   
	[XmlRoot("ChatMessageList"), SerializableAttribute]
    public class ChatMessageList : Entities<ChatMessageBE>
    {}

    [XmlInclude(typeof(ChatMessageBE)), Serializable]
    public class ChatMessageBE:Entity
    {
        #region [Private Members]
                   private System.Int32 _ChatMessageId;

                   private System.String _ChatMessageText;

           private System.DateTime _ChatMessageDate;

           private System.Int32 _ChatRoomId;

           private System.Int32 _ChatUserId;


        #endregion
             
        #region [Properties]
        	#region [ChatMessageId]
	public System.Int32 ChatMessageId
	{
		get { return _ChatMessageId; }
		set { _ChatMessageId = value;}
	}
	#endregion


	#region [ChatMessage]
	public System.String ChatMessageText
	{
        get { return _ChatMessageText; }
        set { _ChatMessageText = value; }
	}
	#endregion


	#region [ChatMessageDate]
	public System.DateTime ChatMessageDate
	{
		get { return _ChatMessageDate; }
		set { _ChatMessageDate = value;}
	}
	#endregion


	#region [ChatRoomId]
	public System.Int32 ChatRoomId
	{
		get { return _ChatRoomId; }
		set { _ChatRoomId = value;}
	}
	#endregion


	#region [ChatUserId]
	public System.Int32 ChatUserId
	{
		get { return _ChatUserId; }
		set { _ChatUserId = value;}
	}
	#endregion



        #endregion
 
    }
    

}
         

   
