//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "pelsoft.FWK_Dsl.ClassDiagram")]

namespace pelsoft.FWK_Dsl
{
	/// <summary>
	/// DomainClass ClassDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("pelsoft.FWK_Dsl.ClassDiagram.DisplayName", typeof(global::pelsoft.FWK_Dsl.FWK_DslDomainModel), "pelsoft.FWK_Dsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("pelsoft.FWK_Dsl.ClassDiagram.Description", typeof(global::pelsoft.FWK_Dsl.FWK_DslDomainModel), "pelsoft.FWK_Dsl.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("5f166212-2a9f-44b9-a829-293f032a6861")]
	public partial class ClassDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Compartment support
		/// <summary>
		/// Whether compartment items change events are subscribed to.
		/// </summary>
		private bool subscribedCompartmentItemsEvents;
		
		/// <summary>
		/// Subscribe to events fired when compartment items changes.
		/// </summary>
		public void SubscribeCompartmentItemsEvents()
		{
			if (!subscribedCompartmentItemsEvents && this.Store != null)
			{
				subscribedCompartmentItemsEvents = true;
				this.Store.EventManagerDirectory.ElementAdded.Add(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Add(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Add(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Add(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
			}
		}
		
		/// <summary>
		/// Unsubscribe to events fired when compartment items changes.
		/// </summary>
		public void UnsubscribeCompartmentItemsEvents()
		{
			if (subscribedCompartmentItemsEvents)
			{
				this.Store.EventManagerDirectory.ElementAdded.Remove(new global::System.EventHandler<DslModeling::ElementAddedEventArgs>(this.CompartmentItemAdded));
				this.Store.EventManagerDirectory.ElementDeleted.Remove(new global::System.EventHandler<DslModeling::ElementDeletedEventArgs>(this.CompartmentItemDeleted));
				this.Store.EventManagerDirectory.ElementPropertyChanged.Remove(new global::System.EventHandler<DslModeling::ElementPropertyChangedEventArgs>(this.CompartmentItemPropertyChanged));
				this.Store.EventManagerDirectory.RolePlayerChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerChangedEventArgs>(this.CompartmentItemRolePlayerChanged));
				this.Store.EventManagerDirectory.RolePlayerOrderChanged.Remove(new global::System.EventHandler<DslModeling::RolePlayerOrderChangedEventArgs>(this.CompartmentItemRolePlayerOrderChanged));
				subscribedCompartmentItemsEvents = false;
			}
		}
		
		#region Event handlers
		/// <summary>
		/// Event for element added.
		/// </summary>
		private void CompartmentItemAdded(object sender, DslModeling::ElementAddedEventArgs e)
		{
			CompartmentItemAddRule.ElementAdded(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element deleted.
		/// </summary>
		private void CompartmentItemDeleted(object sender, DslModeling::ElementDeletedEventArgs e)
		{
			CompartmentItemDeleteRule.ElementDeleted(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for element property changed.
		/// </summary>
		private void CompartmentItemPropertyChanged(object sender, DslModeling::ElementPropertyChangedEventArgs e)
		{
			CompartmentItemChangeRule.ElementPropertyChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player changed.
		/// </summary>
		private void CompartmentItemRolePlayerChanged(object sender, DslModeling::RolePlayerChangedEventArgs e)
		{
			CompartmentItemRolePlayerChangeRule.RolePlayerChanged(e, true /* repaint only */);
		}
		/// <summary>
		/// Event for role-player order changed.
		/// </summary>
		private void CompartmentItemRolePlayerOrderChanged(object sender, DslModeling::RolePlayerOrderChangedEventArgs e)
		{
			CompartmentItemRolePlayerPositionChangeRule.RolePlayerPositionChanged(e, true /* repaint only */);
		}
		#endregion
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Most connectors are mapped to element links, but there can be exceptions. This method tell if a connector should be
		/// mapped to an element link.
		/// </summary>
		public override bool IsConnectorMappedToLink(DslDiagrams::BinaryLinkShape connector)
		{
			#region Check Parameters
			global::System.Diagnostics.Debug.Assert(connector != null);
			if (connector == null)
				throw new global::System.ArgumentNullException("connector");
			#endregion
			if (connector.GetType() == typeof(global::pelsoft.FWK_Dsl.AssociationConnector))
				return false;
			return base.IsConnectorMappedToLink(connector);
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::pelsoft.FWK_Dsl.ModelClass)
			{
				global::pelsoft.FWK_Dsl.ClassShape newShape = new global::pelsoft.FWK_Dsl.ClassShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.ModelInterface)
			{
				global::pelsoft.FWK_Dsl.InterfaceShape newShape = new global::pelsoft.FWK_Dsl.InterfaceShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.MultipleAssociation)
			{
				global::pelsoft.FWK_Dsl.MultipleAssociationShape newShape = new global::pelsoft.FWK_Dsl.MultipleAssociationShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.UnidirectionalAssociation)
			{
				global::pelsoft.FWK_Dsl.UnidirectionalConnector newShape = new global::pelsoft.FWK_Dsl.UnidirectionalConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.BidirectionalAssociation)
			{
				global::pelsoft.FWK_Dsl.BidirectionalConnector newShape = new global::pelsoft.FWK_Dsl.BidirectionalConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.Aggregation)
			{
				global::pelsoft.FWK_Dsl.AggregationConnector newShape = new global::pelsoft.FWK_Dsl.AggregationConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.Composition)
			{
				global::pelsoft.FWK_Dsl.CompositionConnector newShape = new global::pelsoft.FWK_Dsl.CompositionConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.Comment)
			{
				global::pelsoft.FWK_Dsl.CommentBoxShape newShape = new global::pelsoft.FWK_Dsl.CommentBoxShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.MultipleAssociationRole)
			{
				global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnector newShape = new global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.AssociationClassRelationship)
			{
				global::pelsoft.FWK_Dsl.AssociationClassConnector newShape = new global::pelsoft.FWK_Dsl.AssociationClassConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.CommentReferencesSubjects)
			{
				global::pelsoft.FWK_Dsl.CommentConnector newShape = new global::pelsoft.FWK_Dsl.CommentConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.Generalization)
			{
				global::pelsoft.FWK_Dsl.GeneralizationConnector newShape = new global::pelsoft.FWK_Dsl.GeneralizationConnector(this.Partition);
				return newShape;
			}
			if(element is global::pelsoft.FWK_Dsl.Implementation)
			{
				global::pelsoft.FWK_Dsl.ImplementationConnector newShape = new global::pelsoft.FWK_Dsl.ImplementationConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::pelsoft.FWK_Dsl.ClassShape.DecoratorsInitialized += ClassShapeDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.InterfaceShape.DecoratorsInitialized += InterfaceShapeDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.CommentBoxShape.DecoratorsInitialized += CommentBoxShapeDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.UnidirectionalConnector.DecoratorsInitialized += UnidirectionalConnectorDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.BidirectionalConnector.DecoratorsInitialized += BidirectionalConnectorDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.AggregationConnector.DecoratorsInitialized += AggregationConnectorDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.CompositionConnector.DecoratorsInitialized += CompositionConnectorDecoratorMap.OnDecoratorsInitialized;
			global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnector.DecoratorsInitialized += MultipleAssociationRoleConnectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClassShape.
		/// </summary>
		internal static partial class ClassShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClassShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for InterfaceShape.
		/// </summary>
		internal static partial class InterfaceShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for InterfaceShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.NamedElement.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Name").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CommentBoxShape.
		/// </summary>
		internal static partial class CommentBoxShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CommentBoxShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Comment.TextDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Comment").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AssociationConnector.
		/// </summary>
		internal static partial class AssociationConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AssociationConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for UnidirectionalConnector.
		/// </summary>
		internal static partial class UnidirectionalConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for UnidirectionalConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				AssociationConnectorDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceRoleName").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetRoleName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for BidirectionalConnector.
		/// </summary>
		internal static partial class BidirectionalConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for BidirectionalConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				AssociationConnectorDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceRoleName").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetRoleName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AggregationConnector.
		/// </summary>
		internal static partial class AggregationConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AggregationConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				AssociationConnectorDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceRoleName").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetRoleName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for CompositionConnector.
		/// </summary>
		internal static partial class CompositionConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for CompositionConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				AssociationConnectorDecoratorMap.OnDecoratorsInitialized(sender, e);
				
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetMultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.SourceRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "SourceRoleName").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.Association.TargetRoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetRoleName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MultipleAssociationRoleConnector.
		/// </summary>
		internal static partial class MultipleAssociationRoleConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MultipleAssociationRoleConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.MultipleAssociationRole.MultiplicityDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetMultiplicity").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::pelsoft.FWK_Dsl.MultipleAssociationRole.RoleNameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TargetRoleName").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		#region Connect actions
		private global::pelsoft.FWK_Dsl.UnidirectionalAssociationConnectAction unidirectionalAssociationConnectAction;
		private global::pelsoft.FWK_Dsl.BidirectionalAssociationConnectAction bidirectionalAssociationConnectAction;
		private global::pelsoft.FWK_Dsl.AggregationConnectAction aggregationConnectAction;
		private global::pelsoft.FWK_Dsl.CompositionConnectAction compositionConnectAction;
		private global::pelsoft.FWK_Dsl.GeneralizationConnectAction generalizationConnectAction;
		private global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnectAction multipleAssociationRoleConnectAction;
		private global::pelsoft.FWK_Dsl.AssociationClassRelationshipConnectAction associationClassRelationshipConnectAction;
		private global::pelsoft.FWK_Dsl.CommentsReferenceTypesConnectAction commentsReferenceTypesConnectAction;
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.UnidirectionalAssociationFilterString))
				{
					if (this.unidirectionalAssociationConnectAction == null)
					{
						this.unidirectionalAssociationConnectAction = new global::pelsoft.FWK_Dsl.UnidirectionalAssociationConnectAction(this);
						this.unidirectionalAssociationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.unidirectionalAssociationConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.BidirectionalAssociationFilterString))
				{
					if (this.bidirectionalAssociationConnectAction == null)
					{
						this.bidirectionalAssociationConnectAction = new global::pelsoft.FWK_Dsl.BidirectionalAssociationConnectAction(this);
						this.bidirectionalAssociationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.bidirectionalAssociationConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.AggregationFilterString))
				{
					if (this.aggregationConnectAction == null)
					{
						this.aggregationConnectAction = new global::pelsoft.FWK_Dsl.AggregationConnectAction(this);
						this.aggregationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.aggregationConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.CompositionFilterString))
				{
					if (this.compositionConnectAction == null)
					{
						this.compositionConnectAction = new global::pelsoft.FWK_Dsl.CompositionConnectAction(this);
						this.compositionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.compositionConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.GeneralizationFilterString))
				{
					if (this.generalizationConnectAction == null)
					{
						this.generalizationConnectAction = new global::pelsoft.FWK_Dsl.GeneralizationConnectAction(this);
						this.generalizationConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.generalizationConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.MultipleAssociationRoleFilterString))
				{
					if (this.multipleAssociationRoleConnectAction == null)
					{
						this.multipleAssociationRoleConnectAction = new global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnectAction(this);
						this.multipleAssociationRoleConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.multipleAssociationRoleConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.AssociationClassRelationshipFilterString))
				{
					if (this.associationClassRelationshipConnectAction == null)
					{
						this.associationClassRelationshipConnectAction = new global::pelsoft.FWK_Dsl.AssociationClassRelationshipConnectAction(this);
						this.associationClassRelationshipConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.associationClassRelationshipConnectAction;
				} 
				else if (activeView.SelectedToolboxItemSupportsFilterString(global::pelsoft.FWK_Dsl.FWK_DslToolboxHelper.CommentsReferenceTypesFilterString))
				{
					if (this.commentsReferenceTypesConnectAction == null)
					{
						this.commentsReferenceTypesConnectAction = new global::pelsoft.FWK_Dsl.CommentsReferenceTypesConnectAction(this);
						this.commentsReferenceTypesConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.commentsReferenceTypesConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					pointArgs.DiagramClientView.ActiveMouseAction = action;
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				activeView.Toolbox.SelectedToolboxItemUsed();
			}
		}
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.unidirectionalAssociationConnectAction != null)
					{
						this.unidirectionalAssociationConnectAction.Dispose();
						this.unidirectionalAssociationConnectAction = null;
					}
					if(this.bidirectionalAssociationConnectAction != null)
					{
						this.bidirectionalAssociationConnectAction.Dispose();
						this.bidirectionalAssociationConnectAction = null;
					}
					if(this.aggregationConnectAction != null)
					{
						this.aggregationConnectAction.Dispose();
						this.aggregationConnectAction = null;
					}
					if(this.compositionConnectAction != null)
					{
						this.compositionConnectAction.Dispose();
						this.compositionConnectAction = null;
					}
					if(this.generalizationConnectAction != null)
					{
						this.generalizationConnectAction.Dispose();
						this.generalizationConnectAction = null;
					}
					if(this.multipleAssociationRoleConnectAction != null)
					{
						this.multipleAssociationRoleConnectAction.Dispose();
						this.multipleAssociationRoleConnectAction = null;
					}
					if(this.associationClassRelationshipConnectAction != null)
					{
						this.associationClassRelationshipConnectAction.Dispose();
						this.associationClassRelationshipConnectAction = null;
					}
					if(this.commentsReferenceTypesConnectAction != null)
					{
						this.commentsReferenceTypesConnectAction.Dispose();
						this.commentsReferenceTypesConnectAction = null;
					}
					this.UnsubscribeCompartmentItemsEvents();
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#endregion
		#region Constructors, domain class Id
	
		/// <summary>
		/// ClassDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x5f166212, 0x2a9f, 0x44b9, 0xa8, 0x29, 0x29, 0x3f, 0x03, 0x2a, 0x68, 0x61);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClassDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartition : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public ClassDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace pelsoft.FWK_Dsl
{
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.MultipleAssociation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ModelInterface), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ModelClass), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Aggregation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Composition), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.UnidirectionalAssociation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.BidirectionalAssociation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Generalization), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Implementation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Comment), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.MultipleAssociationRole), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.AssociationClassRelationship), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : DslModeling::AddRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (childElement.IsDeleted)
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::pelsoft.FWK_Dsl.MultipleAssociation)
				{
					parentElement = GetParentForMultipleAssociation((global::pelsoft.FWK_Dsl.MultipleAssociation)childElement);
				} else
				if(childElement is global::pelsoft.FWK_Dsl.ModelInterface)
				{
					parentElement = GetParentForModelInterface((global::pelsoft.FWK_Dsl.ModelInterface)childElement);
				} else
				if(childElement is global::pelsoft.FWK_Dsl.ModelClass)
				{
					parentElement = GetParentForModelClass((global::pelsoft.FWK_Dsl.ModelClass)childElement);
				} else
				if(childElement is global::pelsoft.FWK_Dsl.Comment)
				{
					parentElement = GetParentForComment((global::pelsoft.FWK_Dsl.Comment)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::pelsoft.FWK_Dsl.ModelRoot GetParentForModelClass( global::pelsoft.FWK_Dsl.ModelType root )
			{
				// Segments 0 and 1
				global::pelsoft.FWK_Dsl.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::pelsoft.FWK_Dsl.ModelRoot GetParentForModelInterface( global::pelsoft.FWK_Dsl.ModelType root )
			{
				// Segments 0 and 1
				global::pelsoft.FWK_Dsl.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::pelsoft.FWK_Dsl.ModelRoot GetParentForComment( global::pelsoft.FWK_Dsl.Comment root )
			{
				// Segments 0 and 1
				global::pelsoft.FWK_Dsl.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			public static global::pelsoft.FWK_Dsl.ModelRoot GetParentForMultipleAssociation( global::pelsoft.FWK_Dsl.ModelType root )
			{
				// Segments 0 and 1
				global::pelsoft.FWK_Dsl.ModelRoot result = root.ModelRoot;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
		/// <summary>
		/// Rule to update compartments when an item is added to the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemAddRule : DslModeling::AddRule
		{
			/// <summary>
			/// Called when an element is added. 
			/// </summary>
			/// <param name="e"></param>
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				ElementAdded(e, false);
			}
	
			internal static void ElementAdded(DslModeling::ElementAddedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if (e.ModelElement.IsDeleted)
					return;
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ClassHasAttributes)
				{
					global::System.Collections.IEnumerable elements = GetModelClassForClassShapeAttributesCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasAttributes)e.ModelElement);
					UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ClassHasOperations)
				{
					global::System.Collections.IEnumerable elements = GetModelClassForClassShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasOperations)e.ModelElement);
					UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.InterfaceHasOperation)
				{
					global::System.Collections.IEnumerable elements = GetModelInterfaceForInterfaceShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.InterfaceHasOperation)e.ModelElement);
					UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
				}
			}
			
			#region static DomainPath traversal methods to get the list of compartments to update
			internal static global::System.Collections.ICollection GetModelClassForClassShapeAttributesCompartmentFromLastLink(global::pelsoft.FWK_Dsl.ClassHasAttributes root)
			{
				// Segment 0
				global::pelsoft.FWK_Dsl.ModelClass result = root.ModelClass;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelClassForClassShapeAttributesCompartment(global::pelsoft.FWK_Dsl.ModelAttribute root)
			{
				// Segments 1 and 0
				global::pelsoft.FWK_Dsl.ModelClass result = root.ModelClass;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelClassForClassShapeOperationsCompartmentFromLastLink(global::pelsoft.FWK_Dsl.ClassHasOperations root)
			{
				// Segment 0
				global::pelsoft.FWK_Dsl.ModelClass result = root.ModelClass;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelClassForClassShapeOperationsCompartment(global::pelsoft.FWK_Dsl.ClassOperation root)
			{
				// Segments 1 and 0
				global::pelsoft.FWK_Dsl.ModelClass result = root.ModelClass;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelInterfaceForInterfaceShapeOperationsCompartmentFromLastLink(global::pelsoft.FWK_Dsl.InterfaceHasOperation root)
			{
				// Segment 0
				global::pelsoft.FWK_Dsl.ModelInterface result = root.Interface;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			internal static global::System.Collections.ICollection GetModelInterfaceForInterfaceShapeOperationsCompartment(global::pelsoft.FWK_Dsl.InterfaceOperation root)
			{
				// Segments 1 and 0
				global::pelsoft.FWK_Dsl.ModelInterface result = root.Interface;
				if ( result == null ) return new DslModeling::ModelElement[0];
				return new DslModeling::ModelElement[] {result};
			}
			#endregion
	
			#region helper method to update compartments 
			/// <summary>
			/// Updates the compartments for the shapes associated to the given list of model elements
			/// </summary>
			/// <param name="elements">List of model elements</param>
			/// <param name="shapeType">The type of shape that needs updating</param>
			/// <param name="compartmentName">The name of the compartment to update</param>
			/// <param name="repaintOnly">If true, the method will only invalidate the shape for a repaint, without re-initializing the shape.</param>
			internal static void UpdateCompartments(global::System.Collections.IEnumerable elements, global::System.Type shapeType, string compartmentName, bool repaintOnly)
			{
				foreach (DslModeling::ModelElement element in elements)
				{
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
					foreach (DslDiagrams::PresentationElement pel in pels)
					{
						DslDiagrams::CompartmentShape compartmentShape = pel as DslDiagrams::CompartmentShape;
						if (compartmentShape != null && shapeType.IsAssignableFrom(compartmentShape.GetType()))
						{
							if (repaintOnly)
							{
								compartmentShape.Invalidate();
							}
							else
							{
								foreach(DslDiagrams::CompartmentMapping mapping in compartmentShape.GetCompartmentMappings())
								{
									if(mapping.CompartmentId==compartmentName)
									{
										mapping.InitializeCompartmentShape(compartmentShape);
										break;
									}
								}
							}
						}
					}
				}
			}
			#endregion
		}
		
		/// <summary>
		/// Rule to update compartments when an items is removed from the list
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemDeleteRule : DslModeling::DeleteRule
		{
			/// <summary>
			/// Called when an element is deleted
			/// </summary>
			/// <param name="e"></param>
			public override void ElementDeleted(DslModeling::ElementDeletedEventArgs e)
			{
				ElementDeleted(e, false);
			}
			
			internal static void ElementDeleted(DslModeling::ElementDeletedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ClassHasAttributes)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasAttributes)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ClassHasOperations)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasOperations)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.InterfaceHasOperation)
				{
					global::System.Collections.ICollection elements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.InterfaceHasOperation)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when the property on an item being displayed changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ModelAttribute), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.InterfaceOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemChangeRule : DslModeling::ChangeRule 
		{
			/// <summary>
			/// Called when an element is changed
			/// </summary>
			/// <param name="e"></param>
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				ElementPropertyChanged(e, false);
			}
			
			internal static void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ModelAttribute && e.DomainProperty.Id == global::pelsoft.FWK_Dsl.ModelAttribute.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartment((global::pelsoft.FWK_Dsl.ModelAttribute)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.ClassOperation && e.DomainProperty.Id == global::pelsoft.FWK_Dsl.ClassOperation.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartment((global::pelsoft.FWK_Dsl.ClassOperation)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
				}
				if(e.ModelElement is global::pelsoft.FWK_Dsl.InterfaceOperation && e.DomainProperty.Id == global::pelsoft.FWK_Dsl.InterfaceOperation.NameDomainPropertyId)
				{
					global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartment((global::pelsoft.FWK_Dsl.InterfaceOperation)e.ModelElement);
					CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
				}
			}
		}
		
		/// <summary>
		/// Rule to update compartments when a roleplayer change happens
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerChangeRule : DslModeling::RolePlayerChangeRule 
		{
			/// <summary>
			/// Called when the roleplayer on a link changes.
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				RolePlayerChanged(e, false);
			}
			
			internal static void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ModelAttribute)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::pelsoft.FWK_Dsl.ClassShape compartmentShape = pel as global::pelsoft.FWK_Dsl.ClassShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasAttributes)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartment((global::pelsoft.FWK_Dsl.ModelAttribute)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassOperation)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::pelsoft.FWK_Dsl.ClassShape compartmentShape = pel as global::pelsoft.FWK_Dsl.ClassShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[1].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.ClassHasOperations)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartment((global::pelsoft.FWK_Dsl.ClassOperation)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
					}
				}
				if(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(e.DomainRole.IsSource)
					{
						//global::System.Collections.IEnumerable oldElements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.InterfaceOperation)e.OldRolePlayer);
						//foreach(DslModeling::ModelElement element in oldElements)
						//{
						//	DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> pels = DslDiagrams::PresentationViewsSubject.GetPresentation(element);
						//	foreach(DslDiagrams::PresentationElement pel in pels)
						//	{
						//		global::pelsoft.FWK_Dsl.InterfaceShape compartmentShape = pel as global::pelsoft.FWK_Dsl.InterfaceShape;
						//		if(compartmentShape != null)
						//		{
						//			compartmentShape.GetCompartmentMappings()[0].InitializeCompartmentShape(compartmentShape);
						//		}
						//	}
						//}
						
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartmentFromLastLink((global::pelsoft.FWK_Dsl.InterfaceHasOperation)e.ElementLink);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
					}
					else 
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartment((global::pelsoft.FWK_Dsl.InterfaceOperation)e.NewRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// Rule to update compartments when the order of items in the list changes.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation), FireTime=DslModeling::TimeToFire.TopLevelCommit, InitiallyDisabled=true)]
		internal sealed class CompartmentItemRolePlayerPositionChangeRule : DslModeling::RolePlayerPositionChangeRule 
		{
			/// <summary>
			/// Called when the order of a roleplayer in a relationship changes
			/// </summary>
			/// <param name="e"></param>
			public override void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e)
			{
				RolePlayerPositionChanged(e, false);
			}
			
			internal static void RolePlayerPositionChanged(DslModeling::RolePlayerOrderChangedEventArgs e, bool repaintOnly)
			{
				if(e==null) throw new global::System.ArgumentNullException("e");
				if(typeof(global::pelsoft.FWK_Dsl.ClassHasAttributes).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeAttributesCompartment((global::pelsoft.FWK_Dsl.ModelAttribute)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "AttributesCompartment", repaintOnly);
					}
				}
				if(typeof(global::pelsoft.FWK_Dsl.ClassHasOperations).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelClassForClassShapeOperationsCompartment((global::pelsoft.FWK_Dsl.ClassOperation)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.ClassShape), "OperationsCompartment", repaintOnly);
					}
				}
				if(typeof(global::pelsoft.FWK_Dsl.InterfaceHasOperation).IsAssignableFrom(e.DomainRelationship.ImplementationClass))
				{
					if(!e.CounterpartDomainRole.IsSource)
					{
						global::System.Collections.IEnumerable elements = CompartmentItemAddRule.GetModelInterfaceForInterfaceShapeOperationsCompartment((global::pelsoft.FWK_Dsl.InterfaceOperation)e.CounterpartRolePlayer);
						CompartmentItemAddRule.UpdateCompartments(elements, typeof(global::pelsoft.FWK_Dsl.InterfaceShape), "OperationsCompartment", repaintOnly);
					}
				}
			}
		}
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Association), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.MultipleAssociationRole), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.Association.SourceMultiplicityDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.BidirectionalConnector.FindBidirectionalConnectorDecorator("SourceMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.BidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.UnidirectionalConnector.FindUnidirectionalConnectorDecorator("SourceMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.UnidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.AggregationConnector.FindAggregationConnectorDecorator("SourceMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Aggregation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.CompositionConnector.FindCompositionConnectorDecorator("SourceMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Composition.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.Association.TargetMultiplicityDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.BidirectionalConnector.FindBidirectionalConnectorDecorator("TargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.BidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.UnidirectionalConnector.FindUnidirectionalConnectorDecorator("TargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.UnidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.AggregationConnector.FindAggregationConnectorDecorator("TargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Aggregation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.CompositionConnector.FindCompositionConnectorDecorator("TargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Composition.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.Association.SourceRoleNameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.BidirectionalConnector.FindBidirectionalConnectorDecorator("SourceRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.BidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.UnidirectionalConnector.FindUnidirectionalConnectorDecorator("SourceRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.UnidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.AggregationConnector.FindAggregationConnectorDecorator("SourceRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Aggregation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.CompositionConnector.FindCompositionConnectorDecorator("SourceRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Composition.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.Association.TargetRoleNameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.BidirectionalConnector.FindBidirectionalConnectorDecorator("TargetRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.BidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.UnidirectionalConnector.FindUnidirectionalConnectorDecorator("TargetRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.UnidirectionalAssociation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.AggregationConnector.FindAggregationConnectorDecorator("TargetRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Aggregation.DomainClassId);
					}
					decorator = global::pelsoft.FWK_Dsl.CompositionConnector.FindCompositionConnectorDecorator("TargetRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.Composition.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.MultipleAssociationRole.MultiplicityDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnector.FindMultipleAssociationRoleConnectorDecorator("TargetMultiplicity");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.MultipleAssociationRole.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::pelsoft.FWK_Dsl.MultipleAssociationRole.RoleNameDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::pelsoft.FWK_Dsl.MultipleAssociationRoleConnector.FindMultipleAssociationRoleConnectorDecorator("TargetRoleName");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::pelsoft.FWK_Dsl.MultipleAssociationRole.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.BidirectionalAssociation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.UnidirectionalAssociation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Aggregation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Composition), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.MultipleAssociationRole), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.AssociationClassRelationship), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.CommentReferencesSubjects), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Generalization), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::pelsoft.FWK_Dsl.Implementation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::pelsoft.FWK_Dsl.ClassDiagram diagram = linkShape.Diagram as global::pelsoft.FWK_Dsl.ClassDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
