// <autogenerated>
//   This file was generated by T4 code generator ViewModelGenerator.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


var simplecarviewmodel = function()
{
	var self = this;

	//	Type of the original .NET model. Must stay first ! (required for JSON.NET)
	self.$type = 'TRIS.ViewModels.SimpleCarViewModel, TRIS.ViewModels';

	self.brand = ko.observable();
	self.model = ko.observable();
	self.id = ko.observable();
	self.isactive = ko.observable();

	//	invoke the extendable's init() function. Must happen when all observables are created (in case a
    //	computable wants to make use of it)
    this.Initialize();

    self.setModel = function(objFromServer) {
	  if (!objFromServer) return;

	  self.brand(objFromServer.brand);
	  self.model(objFromServer.model);
	  self.id(objFromServer.id);
	  self.isactive(objFromServer.isactive);
	  
	  //	check if change tracking is active for this viewmodel. If it is: reset isDirty flag
	  if (self.isDirty)
		  self.isDirty(false);
    }
}

//	inherit from extendable (will allow adding observables/computables on client-side)
simplecarviewmodel.prototype = new extendable();

