 

	
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a Fwk Code Generator.
//     Runtime Version: 10.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Xml.Serialization;
using System.Collections.Generic;
using System.Text;
using Fwk.Bases;


namespace ss.BE{


	[XmlRoot("GastoBEList"), SerializableAttribute]
    public class GastoBEList :Entities<GastoBE>
    {}
	
	[XmlInclude(typeof(GastoBE)), Serializable]
	public class GastoBE:Entity
	{
			
		 public System.Int32? IdGasto {get;set;}
			
		 public System.Int32? IdPCTipoGasto {get;set;}
			
		 public System.String Descripcion {get;set;}
			
		 public System.DateTime? Fecha {get;set;}
			
		 public System.Double? Monto {get;set;}
			
		 public System.Int32? IdPCFormaPago {get;set;}
			
		 public System.DateTime? FechaCreacion {get;set;}
			
		 public Guid? UserId {get;set;}
						
			
	}
}
