<?xml version="1.0" encoding="utf-8"?>
<Database Name="AdventureWorks" Class="TotalAmountSalesByYearDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=matu\sqlexpress;Initial Catalog=AdventureWorks;Integrated Security=True" SettingsObjectName="DXtraCharts.Properties.Settings" SettingsPropertyName="AdventureWorksConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TotalAmountSalesByYear" Member="TotalAmountSalesByYears">
    <Type Name="TotalAmountSalesByYear">
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </Type>
  </Table>
</Database>