<?xml version="1.0" encoding="utf-8"?>
<Database Name="PUBS" Class="PubsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MATU\SQLEXPRESS;Initial Catalog=PUBS;Integrated Security=True" SettingsObjectName="AnonymusBinding.Properties.Settings" SettingsPropertyName="PUBSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.authors" Member="authors">
    <Type Name="author">
      <Column Name="au_id" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="au_lname" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="au_fname" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="address" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="state" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="zip" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="contract" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="author_titleauthor" Member="titleauthors" ThisKey="au_id" OtherKey="au_id" Type="titleauthor" />
    </Type>
  </Table>
  <Table Name="dbo.titleauthor" Member="titleauthors">
    <Type Name="titleauthor">
      <Column Name="au_id" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title_id" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="au_ord" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="royaltyper" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="author_titleauthor" Member="author" ThisKey="au_id" OtherKey="au_id" Type="author" IsForeignKey="true" />
    </Type>
  </Table>
</Database>