<?xml version="1.0" encoding="utf-8"?><Database Name="EpironChat" EntityNamespace="EpironChat" ContextNamespace="EpironChat" Class="EpironChatDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=CORRSF71DES01;Initial Catalog=EpironChat;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EpironChatConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Security.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserGUID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoweredName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DNI" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="MustChangePassword" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ExternalIdentifier" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Users_RecordCommentTemporary" Member="RecordCommentTemporary" ThisKey="UserId" OtherKey="ModifiedByUserId" Type="RecordCommentTemporary" />
      <Association Name="Users_RecordSets" Member="RecordSets" ThisKey="UserId" OtherKey="ModifiedByUserId" Type="RecordSets" />
    </Type>
  </Table>
  <Table Name="SocialNetwork.RecordCommentTemporary" Member="RecordCommentTemporary">
    <Type Name="RecordCommentTemporary">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="SocialNetworkId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SourcePostDestino" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="PostDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PostedByService" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PCItemType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Error" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RetriesQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ErrorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedByUserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Origen" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="AwaitingUserConfirmation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProcessStart" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ProcessEnd" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="KeepconValidation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Users_RecordCommentTemporary" Member="Users" ThisKey="ModifiedByUserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="SMS.RecordSMS" Member="RecordSMS">
    <Type Name="RecordSMS">
      <Column Name="RecorduserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecordId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceuserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HomePhone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DestinationPhone" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedRecordSMS" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Campaings.RecordSets" Member="RecordSets">
    <Type Name="RecordSets">
      <Column Name="RecordSetId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ActiveFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedByUserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ClosedQuantityGoal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SurveyQuantityGoal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PCRecordSetState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CampaingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddNewRecordFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AllowEditAttributeFlag" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SurveyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImportedRecords" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewRecordsAdded" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RecordsClosed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SurveysCompleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PCObservationType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxDaysScheduleRegister" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClosureStateByMaxDays" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxRecalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClosureStateByRecalls" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ReleaseRecordTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SocialNetworkRequired" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConvertMessageToCase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConvertEMailsToCase" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MergeEmails" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MergeSMS" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ConvertSMSToCase" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Users_RecordSets" Member="Users" ThisKey="ModifiedByUserId" OtherKey="UserId" Type="Users" IsForeignKey="true" />
    </Type>
  </Table>
</Database>