

//------------------------------------------------------------------------------
// <auto-generated>
// 
//
// 
//
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;





namespace ClassLibrary1.EntityFramework
{

    #region Entities

    [XmlRoot("GastoList"), SerializableAttribute]
    public class GastoList : Fwk.Bases.Entities<Gasto> { }

    [XmlInclude(typeof(Gasto)), Serializable]
    public partial class Gasto : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdGasto
        {
            get
            {
                return _IdGasto;
            }
            set
            {
                _IdGasto = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdPCTipoGasto
        {
            get
            {
                return _IdPCTipoGasto;
            }
            set
            {
                _IdPCTipoGasto = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                _Descripcion = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                _Fecha = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.Decimal Monto
        {
            get
            {
                return _Monto;
            }
            set
            {
                _Monto = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdPCFormaPago
        {
            get
            {
                return _IdPCFormaPago;
            }
            set
            {
                _IdPCFormaPago = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return _FechaCreacion;
            }
            set
            {
                _FechaCreacion = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Guid> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                _UserId = value;
            }
        }



        #endregion
    }


    [XmlRoot("TipoParametroList"), SerializableAttribute]
    public class TipoParametroList : Fwk.Bases.Entities<TipoParametro> { }

    [XmlInclude(typeof(TipoParametro)), Serializable]
    public partial class TipoParametro : Fwk.Bases.Entity
    {
        #region Primitive Properties

        /// <summary>
        /// 
        /// </summary>
        public global::System.Int32 IdTipoParametro
        {
            get
            {
                return _IdTipoParametro;
            }
            set
            {
                _IdTipoParametro = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                _Nombre = value;
            }
        }



        /// <summary>
        /// 
        /// </summary>
        public Nullable<global::System.Int32> IdTipoParametroRelacion
        {
            get
            {
                return _IdTipoParametroRelacion;
            }
            set
            {
                _IdTipoParametroRelacion = value;
            }
        }



        #endregion
    }

    #endregion

}
